version: "3.5"

services:
  rabbitmq:
    image: rabbitmq:3.12.10-management-alpine
    platform: linux/x86_64
    restart: always
    ports:
      - "8080:15672" # management
      - "5672:5672" # amqp
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  mongoDb:
    image: mongodb/mongodb-community-server:latest
    platform: linux/x86_64
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
