linters:
  enable:
    - goimports
    - revive
    - gocritic
    - errorlint
    - gomnd
    - misspell
    - testpackage
    - testifylint
    - nlreturn
    - stylecheck
    - wrapcheck

linters-settings:
  staticcheck:
    checks:
      - all
      - '-SA1000' # disable the rule SA1000
      - '-SA1004' # disable the rule SA1004
      - '-SA1024' # disable the rule SA1024
